# Generated by Django 3.1.3 on 2021-02-25 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_type', models.CharField(choices=[('ENTRY INPUT', 'ENTRY INPUT'), ('OPTION SELECT', 'OPTION SELECT'), ('FREE ENTRY', 'FREE ENTRY'), ('DYNAMIC MENU', 'DYNAMIC MENU')], max_length=20)),
                ('label_en', models.CharField(max_length=256)),
                ('label_sw', models.CharField(max_length=256)),
                ('next_menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ussd.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_en', models.CharField(max_length=256)),
                ('label_sw', models.CharField(max_length=256)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ussd.menu')),
                ('next_menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ussd.menu')),
            ],
        ),
    ]
