# Generated by Django 3.1.3 on 2021-02-26 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='next_menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='parent_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='ussd.menu'),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
