# Generated by Django 3.1.3 on 2020-11-09 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Active', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(max_length=20, unique=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('bank_id', models.CharField(max_length=10)),
                ('account_number', models.CharField(max_length=20)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.consumer')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=20)),
                ('file_reference_id', models.CharField(max_length=10)),
                ('total_amount', models.CharField(max_length=20)),
                ('count_of_records', models.IntegerField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('timestamp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=20)),
                ('bank_id', models.CharField(max_length=10)),
                ('account_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('result_code', models.CharField(max_length=20, null=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.consumer')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.customer')),
            ],
            options={
                'unique_together': {('reference_number', 'consumer')},
            },
        ),
    ]
