# Generated by Django 3.1.3 on 2020-11-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=20)),
                ('timestamp', models.CharField(max_length=38)),
                ('file_reference_id', models.CharField(max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=40)),
                ('count_of_records', models.IntegerField()),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
