# Generated by Django 3.1.3 on 2020-11-10 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_paymentfile_consumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentfile',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.consumer'),
        ),
    ]
