# Generated by Django 3.1.3 on 2020-11-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201110_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentfile',
            name='file_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
