# Generated by Django 3.1.3 on 2020-11-30 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201127_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='approval_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='command',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='recorded_at',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='request',
            field=models.CharField(default='Initiated', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
