# Generated by Django 3.1.3 on 2020-11-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201130_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_number_req',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_id_req',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
