# Generated by Django 3.1.3 on 2020-12-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201130_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='msisdn',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='consumer',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
