# Generated by Django 3.1.3 on 2020-12-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201202_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileentry',
            name='signature',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
