# Generated by Django 3.1.3 on 2020-12-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fileentry_signature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumer',
            old_name='msisdn',
            new_name='tp_username',
        ),
        migrations.AddField(
            model_name='payment',
            name='trans_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
