# Generated by Django 3.1.3 on 2020-12-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201212_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileentry',
            old_name='file_name',
            new_name='file_name_in',
        ),
        migrations.AddField(
            model_name='fileentry',
            name='file_name_out',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
