# Generated by Django 3.1.3 on 2021-03-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210217_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileentry',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=38),
        ),
    ]
